---
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: echo "Nothing to do here"
  test:
    docker:
      - image: circleci/node:16.11.1
    steps:
      - checkout
      - run: echo "Nothing to do here"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
